export const LOAD_APPS_START = 'LOAD_APPS_START';
export const LOAD_APPS_SUCCESS = 'LOAD_APPS_SUCCESS';
export const CREATE_APP_CATE = 'CREATE_APP_CATE';
export const UPDATE_APP_CATE = 'UPDATE_APP_CATE';
export const DELETE_APP_CATE = 'DELETE_APP_CATE';

export const LOAD_ACCOUNT_SUCCESS = 'LOAD_ACCOUNT_SUCCESS';
export const LOAD_ACCOUNT_START = 'LOAD_ACCOUNT_START';
export const CREATE_ACCOUNT_START = 'CREATE_ACCOUNT_START';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAIL = 'CREATE_ACCOUNT_FAIL';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';

export const DONG_BO_SUCCESS = 'DONG_BO_SUCCESS';
export const DONG_BO_FAIL = 'DONG_BO_FAIL';
export const DONG_BO_START = 'DONG_BO_START';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUHT_FAIL';

export const DONG_BO_APPS = 'DONG_BO_APPS';
export const DONG_BO_ACCS = 'DONG_BO_ACCS';